language: java

# The default JDK is 7 if unspecified, and we need 8
jdk:
  - oraclejdk8

# By default, the Travis container-based mode runs jdk1.8.0_31 (which is too old for this build)
addons:
  apt:
    packages:
    - oracle-java8-installer